mod get_access;
mod landing;
mod legal_notice;
mod login;
mod logout;
mod privacy;
mod repo;
mod repos;
mod settings;
mod task;
mod tasks;

pub use get_access::WaitlistPage;
pub use landing::LandingPage;
pub use legal_notice::LegalNoticePage;
pub use login::LoginPage;
pub use logout::LogoutPage;
pub use privacy::PrivacyPage;
pub use repo::RepoPage;
pub use repos::ReposPage;
pub use settings::SettingsPage;
pub use task::TaskPage;
pub use tasks::TasksPage;
